[build]
  base = "fpl-front-end"
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm run start-netlify" # Adjust this based on your setup
  functions = "netlify/functions/"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"